### PR TITLE
Resolving conflicts for "Assorted improvements to the gem's dependencies"

### PR DESCRIPTION
**Pull request by maxjacobson**
👋 Hi there

This is another take of #2. I resolved the conflicts, and updated the test matrix to ensure that the fixes worked.

Just interloping, because I noticed that my Gemfile.lock has quite an old version of the `rails` gem. In one project, we do the "custom stack" thing where we depend on the rails libraries directly, rather than rails itself. The old version of rails led to [GitHub's new security vulnerability feature](https://github.com/blog/2470-introducing-security-alerts-on-github) warning us about an insecure dependency. It seems that this gem's direct dependence on rails is what's throwing us off.

Thanks for the gem!

(cc @lucasmazza @jonrohan)

### CODE REVIEW

**Comment by maxjacobson** [comment]
I'm not seeing the tests running for this pull request (maybe it's set not to run for forks?) but I added my fork to travis just to double check the config, and it seems to work (https://travis-ci.org/maxjacobson/octicons_helper/builds)

**Comment by maxjacobson** [comment]
Btw... I noticed that [the latest release on rubygems](https://rubygems.org/gems/octicons_helper/versions/4.0.7) seems to be newer than [the latest release on GitHub](https://github.com/primer/octicons_helper/releases/tag/v4.0.1). Ideally those changes could be pushed up, to make sure this change is up-to-date.

**Comment by jonrohan** [comment]
Thanks for this! I hate to pull the rug out from underneath you on this PR, but we've moved the gem into a monorepo to help with cutting new versions and developing more efficiently. 

The code [lives here now](https://github.com/primer/octicons/tree/master/lib/octicons_helper) I'll update the incorrect links you found in the gemspec. 

I can update the code with your changes if you like, but I'm unsure how to port and give you credit. If you're fine with me taking the commits, I'll make the updates. If you'd like to keep credit can you reopen this pr over there?

**Comment by maxjacobson** [comment]
Aha, that explains where the source for the latest releases lives.

No credit needed (if anything, that should go to @lucasmazza anyway 😉), just happy to revive the conversation. If you don't mind changing the gem to depend on specific libraries instead of rails, we would definitely appreciate that. Updating the homepage to point to the monorepo would also be helpful for the next person.

Cheers

**Pull request closed without merging**
